name: "DiscordPlayerList"
version: 1.1.1
main: dev.iamgabriel.DiscordMinecraftOnlinePlugin.Plugin
description: A plugin that shows the players online on the server in a discord message.
author: iamgabrieltv
website: https://github.com/iamgabrieltv/DiscordMinecraftOnlinePlugin
api-version: "1.21.11"